create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  appointment_type text not null
    check (appointment_type in ('in_person', 'phone')),
  starts_at timestamptz not null unique,
  created_at timestamptz not null default now()
);

alter table public.appointments enable row level security;
